repos:
-   repo: https://github.com/matthewhughes934/pre-commit-format-markdown
    rev: v0.5.0
    hooks:
    -   id: format-markdown-docker
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.62.0
    hooks:
    -   id: golangci-lint-full
        language_version: "1.23.0"
-   repo: https://gitlab.com/matthewhughes/common-changelog
    rev: v0.2.0
    hooks:
    -   id: validate-changelog
-   repo: https://github.com/matthewhughes934/golines
    rev: v0.12.0
    hooks:
    -   id: golines
        exclude: testdata
-   repo: https://gitlab.com/matthewhughes/go-pre-commit
    rev: v0.3.0
    hooks:
    -   id: go-mod-tidy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
